/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semtask;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.swing.*;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Admin
 */
public class AddFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddFrame
     */
    public AddFrame() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        RLabel1 = new javax.swing.JLabel();
        RLabel2 = new javax.swing.JLabel();
        RTextField1 = new javax.swing.JTextField();
        RLabel3 = new javax.swing.JLabel();
        RTextField2 = new javax.swing.JTextField();
        RTextField3 = new javax.swing.JTextField();
        RLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Создание новой фигуры");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Отрезок", "Ломанная", "Окружность", "Многоугольник", "Треугольник", "Четырёхугольник", "Прямоугольник", "Трапеция" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSelected(evt);
            }
        });

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Отмена");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("1 точка");

        jLabel2.setText("x:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("y:");

        jLabel4.setText("2 точка");

        jLabel5.setText("x:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setText("y:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setText("4 точка");

        jLabel8.setText("х:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel9.setText("у:");

        jTextField7.setToolTipText("");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        RLabel1.setText("Точка радиуса");

        RLabel2.setText("x:");

        RLabel3.setText("y:");

        RLabel4.setText("Радиус");

        jLabel11.setText("x:");

        jLabel10.setText("3 точка");

        jLabel12.setText("у:");

        jTextField8.setToolTipText("");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel13.setText("5 точка");

        jLabel14.setText("х:");

        jLabel15.setText("у:");

        jLabel16.setText("6 точка");

        jLabel17.setText("х:");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel18.setText("у:");

        jLabel19.setText("7 точка");

        jLabel20.setText("х:");

        jLabel21.setText("у:");

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jLabel22.setText("8 точка");

        jLabel23.setText("х:");

        jLabel24.setText("у:");

        jLabel2.setVisible(false);
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jLabel2.setVisible(false);}
        else{jLabel2.setVisible(true);}
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jTextField2.setVisible(false);}
        else{jTextField2.setVisible(true);}
        jLabel3.setVisible(false);
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jLabel3.setVisible(false);}
        else{jLabel3.setVisible(true);}
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jTextField3.setVisible(false);}
        else{jTextField3.setVisible(true);}
        jLabel4.setVisible(false);
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jLabel4.setVisible(false);}
        else{jLabel4.setVisible(true);}
        jLabel5.setVisible(false);
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jLabel5.setVisible(false);}
        else{jLabel5.setVisible(true);}
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jTextField4.setVisible(false);}
        else{jTextField4.setVisible(true);}
        jLabel6.setVisible(false);
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jLabel6.setVisible(false);}
        else{jLabel6.setVisible(true);}
        if(jComboBox1.getSelectedItem() == "Окружность"){
            jTextField5.setVisible(false);}
        else{jTextField5.setVisible(true);}

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(355, 355, 355)
                                        .addComponent(RLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(RLabel1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(391, 391, 391)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RLabel4)))))
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel19))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel22))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField14))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField16)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RLabel2)
                                .addComponent(RTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RLabel3)
                                .addComponent(RTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(RLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jComboBox1.getSelectedItem() == "Отрезок"){
         double x1 = Double.parseDouble( jTextField2.getText().replace(",",".") );
         double y1 = Double.parseDouble( jTextField3.getText().replace(",",".") );
         double x2 = Double.parseDouble( jTextField4.getText().replace(",",".") );
         double y2 = Double.parseDouble( jTextField5.getText().replace(",",".") );   
            
 
          double[] array = new double[]{x1,y1};
          Point2D point2d1 = new Point2D(array);
          double[] array2 = new double[]{x2,y2};
          Point2D point2d2 = new Point2D(array2);
          Segment segment = new Segment(point2d1,point2d2);
          /*g.drawLine(point2d1.x[0],point2d1.x[1], point2d2.x[0], point2d2.x[1]);
          MainFrame mainframe = new MainFrame();
          Graphics g;*/

          MainFrame mainframe = new MainFrame();
          mainframe.shapes.addAll(container1);
          mainframe.shapes.add(segment);
            FlowLayout experimentLayout = new FlowLayout();
            mainframe.setLayout(experimentLayout);
          mainframe.setVisible(true);

          this.dispose();
          showMessageDialog(null,"Фигура добавлена");
          
        }
        if(jComboBox1.getSelectedItem() == "Окружность"){
            double x1 = Double.parseDouble( RTextField1.getText().replace(",",".") );
            double y1 = Double.parseDouble( RTextField2.getText().replace(",",".") );
            double r = Double.parseDouble( RTextField3.getText().replace(",",".") );
            double[] rarray = new double[]{x1,y1};
            Point2D point2d = new Point2D(rarray);
            Circle circle = new Circle(point2d,r);
            MainFrame mainframe = new MainFrame();
            FlowLayout experimentLayout = new FlowLayout();
            mainframe.setLayout(experimentLayout);
            mainframe.shapes.addAll(container1);
            mainframe.shapes.add(circle);
            mainframe.setVisible(true);
            this.dispose();
            showMessageDialog(null,"Фигура добавлена");
        }
        if(jComboBox1.getSelectedItem() == "Ломанная"){
         double x1 = Double.parseDouble( jTextField2.getText().replace(",",".") );
         double y1 = Double.parseDouble( jTextField3.getText().replace(",",".") );
         double x2 = Double.parseDouble( jTextField4.getText().replace(",",".") );
         double y2 = Double.parseDouble( jTextField5.getText().replace(",",".") ); 
        
          double x3 = Double.parseDouble( jTextField6.getText().replace(",",".") );
         double y3 = Double.parseDouble( jTextField7.getText().replace(",",".") );
        double[] array3 = new double[]{x3,y3};
        Point2D point2d3 = new Point2D(array3);
        
        
        
           double x4 = Double.parseDouble( jTextField1.getText().replace(",",".") );
         double y4 = Double.parseDouble( jTextField8.getText().replace(",",".") );
        double[] array4 = new double[]{x4,y4};
        Point2D point2d4 = new Point2D(array4);
        
        
        
         double x5 = Double.parseDouble( jTextField9.getText().replace(",",".") );
         double y5 = Double.parseDouble( jTextField10.getText().replace(",",".") );
        double[] array5 = new double[]{x5,y5};
        Point2D point2d5 = new Point2D(array5);
        
        
        
          double[] array = new double[]{x1,y1};
          Point2D point2d1 = new Point2D(array);
          double[] array2 = new double[]{x2,y2};
         
          Point2D point2d2 = new Point2D(array2);
          Point2D[] points2d = new Point2D[]{point2d1,point2d2,point2d3,point2d4,point2d5};
          Polyline polyline = new Polyline(points2d);
          polyline.n =(int) jSpinner1.getValue();
          MainFrame mainframe = new MainFrame();
          mainframe.shapes.addAll(container1);
          mainframe.shapes.add(polyline);
            FlowLayout experimentLayout = new FlowLayout();
            mainframe.setLayout(experimentLayout);
          showMessageDialog(null,"Фигура добавлена");
          mainframe.setVisible(true);
          this.dispose();
        }
        if(jComboBox1.getSelectedItem() == "Многоугольник"){
            double x1 = Double.parseDouble( jTextField2.getText().replace(",",".") );
         double y1 = Double.parseDouble( jTextField3.getText().replace(",",".") );
         double x2 = Double.parseDouble( jTextField4.getText().replace(",",".") );
         double y2 = Double.parseDouble( jTextField5.getText().replace(",",".") ); 
        
          double x3 = Double.parseDouble( jTextField6.getText().replace(",",".") );
         double y3 = Double.parseDouble( jTextField7.getText().replace(",",".") );
        double[] array3 = new double[]{x3,y3};
        Point2D point2d3 = new Point2D(array3);
        
        
        
           double x4 = Double.parseDouble( jTextField1.getText().replace(",",".") );
         double y4 = Double.parseDouble( jTextField8.getText().replace(",",".") );
        double[] array4 = new double[]{x4,y4};
        Point2D point2d4 = new Point2D(array4);
        
        
        
         double x5 = Double.parseDouble( jTextField9.getText().replace(",",".") );
         double y5 = Double.parseDouble( jTextField10.getText().replace(",",".") );
        double[] array5 = new double[]{x5,y5};
        Point2D point2d5 = new Point2D(array5);
        
        
        
          double[] array = new double[]{x1,y1};
          Point2D point2d1 = new Point2D(array);
          double[] array2 = new double[]{x2,y2};
         
          Point2D point2d2 = new Point2D(array2);
          Point2D[] points2d = new Point2D[]{point2d1,point2d2,point2d3,point2d4,point2d5};
          NGon ngon = new NGon(points2d);
          ngon.n = 5;
          MainFrame mainframe = new MainFrame();
            FlowLayout experimentLayout = new FlowLayout();
            mainframe.setLayout(experimentLayout);
          mainframe.shapes.addAll(container1);
          mainframe.shapes.add(ngon);
          showMessageDialog(null,"Фигура добавлена");
          mainframe.setVisible(true);
          this.dispose();
        }
        if(jComboBox1.getSelectedItem() == "Треугольник"){
            
            double x1 = Double.parseDouble( jTextField2.getText().replace(",",".") );
         double y1 = Double.parseDouble( jTextField3.getText().replace(",",".") );
         double x2 = Double.parseDouble( jTextField4.getText().replace(",",".") );
         double y2 = Double.parseDouble( jTextField5.getText().replace(",",".") ); 
        
          double x3 = Double.parseDouble( jTextField6.getText().replace(",",".") );
         double y3 = Double.parseDouble( jTextField7.getText().replace(",",".") );
        double[] array3 = new double[]{x3,y3};
        Point2D point2d3 = new Point2D(array3);
        
        
        
        
        
          double[] array = new double[]{x1,y1};
          Point2D point2d1 = new Point2D(array);
          double[] array2 = new double[]{x2,y2};
         
          Point2D point2d2 = new Point2D(array2);
          Point2D[] points2d = new Point2D[]{point2d1,point2d2,point2d3};
          TGon trigon = new TGon(points2d);
          trigon.n = 3;
          MainFrame mainframe = new MainFrame();
            FlowLayout experimentLayout = new FlowLayout();
            mainframe.setLayout(experimentLayout);
          mainframe.shapes.addAll(container1);
          mainframe.shapes.add(trigon);
          showMessageDialog(null,"Фигура добавлена");
          mainframe.setVisible(true);
          this.dispose();
        }
        if(jComboBox1.getSelectedItem() == "Четырёхугольник"){
            double x1 = Double.parseDouble( jTextField2.getText().replace(",",".") );
         double y1 = Double.parseDouble( jTextField3.getText().replace(",",".") );
         double x2 = Double.parseDouble( jTextField4.getText().replace(",",".") );
         double y2 = Double.parseDouble( jTextField5.getText().replace(",",".") ); 
        
          double x3 = Double.parseDouble( jTextField6.getText().replace(",",".") );
         double y3 = Double.parseDouble( jTextField7.getText().replace(",",".") );
        double[] array3 = new double[]{x3,y3};
        Point2D point2d3 = new Point2D(array3);
        
        
        
           double x4 = Double.parseDouble( jTextField1.getText().replace(",",".") );
         double y4 = Double.parseDouble( jTextField8.getText().replace(",",".") );
        double[] array4 = new double[]{x4,y4};
        Point2D point2d4 = new Point2D(array4);
        
      
        
        
        
          double[] array = new double[]{x1,y1};
          Point2D point2d1 = new Point2D(array);
          double[] array2 = new double[]{x2,y2};
         
          Point2D point2d2 = new Point2D(array2);
          Point2D[] points2d = new Point2D[]{point2d1,point2d2,point2d3,point2d4};
          QGon qgon = new QGon(points2d);
          qgon.n = 4;
          MainFrame mainframe = new MainFrame();
            FlowLayout experimentLayout = new FlowLayout();
            mainframe.setLayout(experimentLayout);
          mainframe.shapes.addAll(container1);
          showMessageDialog(null,"Фигура добавлена");
          mainframe.shapes.add(qgon);
          mainframe.setVisible(true);
          this.dispose();
        }
        if(jComboBox1.getSelectedItem() == "Прямоугольник"){
           double x1 = Double.parseDouble( jTextField2.getText().replace(",",".") );
         double y1 = Double.parseDouble( jTextField3.getText().replace(",",".") );
         double x2 = Double.parseDouble( jTextField4.getText().replace(",",".") );
         double y2 = Double.parseDouble( jTextField5.getText().replace(",",".") ); 
        
          double x3 = Double.parseDouble( jTextField6.getText().replace(",",".") );
         double y3 = Double.parseDouble( jTextField7.getText().replace(",",".") );
        double[] array3 = new double[]{x3,y3};
        Point2D point2d3 = new Point2D(array3);
        
        
        
           double x4 = Double.parseDouble( jTextField1.getText().replace(",",".") );
         double y4 = Double.parseDouble( jTextField8.getText().replace(",",".") );
        double[] array4 = new double[]{x4,y4};
        Point2D point2d4 = new Point2D(array4);
        
      
        
        
        
          double[] array = new double[]{x1,y1};
          Point2D point2d1 = new Point2D(array);
          double[] array2 = new double[]{x2,y2};
         
          Point2D point2d2 = new Point2D(array2);
          Point2D[] points2d = new Point2D[]{point2d1,point2d2,point2d3,point2d4};
          Rectangle rectangle = new Rectangle(points2d);
          rectangle.n = 4;
          MainFrame mainframe = new MainFrame();
          mainframe.shapes.addAll(container1);
          mainframe.shapes.add(rectangle);
          showMessageDialog(null,"Фигура добавлена");
          mainframe.setVisible(true);
          this.dispose();
        }
        if(jComboBox1.getSelectedItem() == "Трапеция"){
            double x1 = Double.parseDouble( jTextField2.getText().replace(",",".") );
         double y1 = Double.parseDouble( jTextField3.getText().replace(",",".") );
         double x2 = Double.parseDouble( jTextField4.getText().replace(",",".") );
         double y2 = Double.parseDouble( jTextField5.getText().replace(",",".") ); 
        
          double x3 = Double.parseDouble( jTextField6.getText().replace(",",".") );
         double y3 = Double.parseDouble( jTextField7.getText().replace(",",".") );
        double[] array3 = new double[]{x3,y3};
        Point2D point2d3 = new Point2D(array3);
        
        
        
           double x4 = Double.parseDouble( jTextField1.getText().replace(",",".") );
         double y4 = Double.parseDouble( jTextField8.getText().replace(",",".") );
        double[] array4 = new double[]{x4,y4};
        Point2D point2d4 = new Point2D(array4);
        
      
        
        
        
          double[] array = new double[]{x1,y1};
          Point2D point2d1 = new Point2D(array);
          double[] array2 = new double[]{x2,y2};
         
          Point2D point2d2 = new Point2D(array2);
          Point2D[] points2d = new Point2D[]{point2d1,point2d2,point2d3,point2d4};
          Trapeze trapeze = new Trapeze(points2d);
          trapeze.n = 4;
          MainFrame mainframe = new MainFrame();
          mainframe.shapes.addAll(container1);
          mainframe.shapes.add(trapeze);
          showMessageDialog(null,"Фигура добавлена");
          mainframe.setVisible(true);
          this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      AddFrame.this.dispose();
      MainFrame mainframe = new MainFrame();
      mainframe.shapes.addAll(container1);
      mainframe.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ItemSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSelected

    if(jComboBox1.getSelectedItem() == "Окружность"){
    jLabel1.setVisible(false);
    jLabel2.setVisible(false);
    jLabel3.setVisible(false);
    jLabel4.setVisible(false);
    jLabel5.setVisible(false);
    jLabel6.setVisible(false);
    jLabel7.setVisible(false);
    jLabel8.setVisible(false);
    jLabel9.setVisible(false);
    jLabel10.setVisible(false);
    jLabel11.setVisible(false);
    jLabel12.setVisible(false);
    jLabel13.setVisible(false);
    jLabel14.setVisible(false);
    jLabel15.setVisible(false);
        jLabel16.setVisible(false);
    jLabel7.setVisible(false);
    jLabel8.setVisible(false);
    jLabel19.setVisible(false);
    jLabel20.setVisible(false);
    jLabel21.setVisible(false);
    jLabel22.setVisible(false);
    jLabel23.setVisible(false);
    jLabel24.setVisible(false);
    jTextField1.setVisible(false);
    jTextField2.setVisible(false);
    jTextField3.setVisible(false);
    jTextField4.setVisible(false);
    jTextField5.setVisible(false);
    jTextField6.setVisible(false);
    jTextField7.setVisible(false);
    jTextField8.setVisible(false);
    jTextField9.setVisible(false);
    jTextField10.setVisible(false);
     jTextField11.setVisible(false);
    jTextField12.setVisible(false);
    jTextField13.setVisible(false);
    jTextField14.setVisible(false);
    jTextField15.setVisible(false);
    jTextField16.setVisible(false);
    
    }
    else{jLabel1.setVisible(true);
    jLabel2.setVisible(true);
    jLabel3.setVisible(true);
    jLabel4.setVisible(true);
    jLabel5.setVisible(true);
    jLabel6.setVisible(true);
    jLabel7.setVisible(true);
    jLabel8.setVisible(true);
    jLabel9.setVisible(true);
    jLabel10.setVisible(true);
    jLabel11.setVisible(true);
    jLabel12.setVisible(true);
    jLabel13.setVisible(true);
    jLabel14.setVisible(true);
    jLabel15.setVisible(true);
    jTextField1.setVisible(true);
    jTextField2.setVisible(true);
    jTextField3.setVisible(true);
    jTextField4.setVisible(true);
    jTextField5.setVisible(true);
    jTextField6.setVisible(true);
    jTextField7.setVisible(true);
    jTextField8.setVisible(true);
    jTextField9.setVisible(true);
    jTextField10.setVisible(true);
    jTextField11.setVisible(true);
    jTextField12.setVisible(true);
    jTextField13.setVisible(true);
    jTextField14.setVisible(true);
    jTextField15.setVisible(true);
    jTextField16.setVisible(true);
     jLabel7.setVisible(true);
    jLabel8.setVisible(true);
    jLabel19.setVisible(true);
    jLabel20.setVisible(true);
    jLabel21.setVisible(true);
    jLabel22.setVisible(true);
    jLabel23.setVisible(true);
    jLabel24.setVisible(true);
    }
    

    
    if((jComboBox1.getSelectedItem() == "Ломанная") | (jComboBox1.getSelectedItem() == "Многоугольник")){
    jSpinner1.setVisible(true);}
    else{jSpinner1.setVisible(false);}
    
    
    if(jComboBox1.getSelectedItem() == "Окружность"){
        RLabel1.setVisible(true);
        RLabel2.setVisible(true);
        RLabel3.setVisible(true);
        RTextField1.setVisible(true);
        RTextField2.setVisible(true);
        RTextField3.setVisible(true);
        RLabel4.setVisible(true);
    }else{
        RLabel1.setVisible(false);
        RLabel2.setVisible(false);
        RLabel3.setVisible(false);
        RTextField1.setVisible(false);
        RTextField2.setVisible(false);
        RTextField3.setVisible(false);
        RLabel4.setVisible(false);
    }
         
    }//GEN-LAST:event_ItemSelected

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RLabel1;
    private javax.swing.JLabel RLabel2;
    private javax.swing.JLabel RLabel3;
    private javax.swing.JLabel RLabel4;
    private javax.swing.JTextField RTextField1;
    private javax.swing.JTextField RTextField2;
    private javax.swing.JTextField RTextField3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
List<IShape> container1 = new ArrayList<>();
}
